extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_dirt2d_lights;
extern Lights1 ssl_dl_dirt_slippery_lights;
extern Lights1 ssl_dl_dirt_lights;
extern Lights1 ssl_dl_rock_lights;
extern u8 ssl_dl_d64_tuti_64x64_ci4_ci4[];
extern u8 ssl_dl_d64_tuti_64x64_ci4_ci4_pal_rgba16[];
extern u8 ssl_dl_Rock_06_02_64x64_ci4_ci4[];
extern u8 ssl_dl_Rock_06_02_64x64_ci4_ci4_pal_rgba16[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_0[14];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_2[4];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx ssl_dl_oob_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_oob_mesh_layer_1_vtx_0[125];
extern Gfx ssl_dl_oob_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Volcano_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_Volcano_mesh_layer_1_vtx_0[90];
extern Gfx ssl_dl_Volcano_mesh_layer_1_tri_0[];
extern Gfx mat_ssl_dl_dirt2d[];
extern Gfx mat_revert_ssl_dl_dirt2d[];
extern Gfx mat_ssl_dl_dirt_slippery[];
extern Gfx mat_revert_ssl_dl_dirt_slippery[];
extern Gfx mat_ssl_dl_dirt[];
extern Gfx mat_revert_ssl_dl_dirt[];
extern Gfx mat_ssl_dl_rock[];
extern Gfx mat_revert_ssl_dl_rock[];
extern Gfx ssl_dl_Cube_mesh_layer_1[];
extern Gfx ssl_dl_oob_mesh_layer_1[];
extern Gfx ssl_dl_Volcano_mesh_layer_1[];
extern Gfx ssl_dl_material_revert_render_settings[];
